input {
  file {
    path => "/var/lib/docker/containers/*/*-json.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
    tags => ["docker-json"]
  }
}

filter {
  if [log] =~ /"service":"(sample-app|nginx)"/ {
    json {
      source => "log"
      target => "app_log"
      skip_on_invalid_json => true
    }
  }
  if [time] {
    date {
      match => ["time", "ISO8601"]
      target => "@timestamp"
    }
  }
  mutate {
    add_field => {
      "[@metadata][target_index]" => "docker-logs-%{+YYYY.MM.dd}"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][target_index]}"
    ilm_enabled => false
  }
  stdout { codec => dots }
}
